# Model hyperparameters
model:
  # Residual block parameters
  number_of_residual_blocks: 4
  number_of_filters: 3

  # Hidden layer hyper parameters
  number_of_hidden_layers: 2
  number_of_neurons: 128

  # head hyper parameters
  value_head_filters: 8
  policy_head_filters: 24

  # General hyper parameters
  perform_batch_norm: False
  dropout_rate: 0.01

  path_to_model_cache: "models/"

# Game hyperparameters
game:
  size: 9
  komi: 4.5
  maximum_number_of_moves: 180
  moves_given_to_model: 5

# Data parameters
data:
  path_to_database: "data/"
  window: 100
  games_per_generation: 81

# Training parameters
training:
  epochs: 100
  lr: 0.002  # TODO: Experiment with sliding windows
  batch_size: 128
  weight_decay: 0.00005

# Model inputs (legal moves, player stones, opponent stones, moves_given_to_model x previus moves, liberties)
